### ISSUE TITLE
ship from china?

### ISSUE THREAD

**Issue by ntn888** [jpconstantineau/BlueMicro833_hardware#1]
hi do you provide shipment from china? i guess in this case the worldwide shipment will be lower cost?

**Comment by ntn888** [comment]
[this](https://www.aliexpress.com/item/1005001570735448.html?algo_exp_id=c9952087-fe8f-4feb-b922-9dff5244d0b8-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000016631331813%22%7D&pdp_pi=-1%3B6.52%3B-1%3B-1%40salePrice%3BAUD%3Bsearch-mainSearch) store in aliexpress sells these modules for ~5usd.
together with your breakout board at 5usd, the whole thing is very reasonable price for someone beginning with the nRF chips!
but the shipping from canada is quite an overhead...

**Comment by ntn888** [comment]
this is in comparison to the feather boards that go for over $40; that's why i'm interested in your solution.

**Comment by jpconstantineau** [comment]
I am located in Canada and I don't ship from China. I can send a PayPal invoice to avoid tindie fees and thus lower your overall cost (including shipping costs too but not to the low price of shipping from China) let me know if you are interested and contact me by email (it's on my GitHub profile) if you are interested in going for a PayPal invoice instead.

**Comment by ntn888** [comment]
i'm interested in getting a Zephyr ported to this simple board...
as a plus this will get the board listed on their [list](https://docs.zephyrproject.org/latest/boards/index.html) free publicity...

**Comment by ntn888** [comment]
if it does indeed catch on.. you may consider doing a proper supply chain i guess :)
